### ISSUE TITLE
Non-dark theme shows white text on white background

### ISSUE THREAD

**Issue by drossberg** [insilmaril/vym#80]
- compiled from source (development branch) with Visual Studio 2019 and Qt 5.15.1,
- installed, and
- started the program

![vym_white-on-white](https://github.com/insilmaril/vym/assets/33295041/b0597234-e6ce-460a-8658-49163efc75ed)

**Comment by insilmaril** [comment]
Fixed with #81

**Comment by lobre** [comment]
Sorry to comment on a closed issue, but I also see the same problem with the latest HEAD. The last above comment says that it was supposed to be fixed with #81, but this PR was closed without merging.

As of today, with the light theme, I still see mapcenter drawn white-on-white.

Am I missing something?

**Comment by insilmaril** [comment]
The settings in MapDesign are currently used just as fallback, so the merge should not be necessary. Initial settings are loaded from the default.vym and default-dark.vym maps in demos/ directory.

**Comment by lobre** [comment]
> Initial settings are loaded from the default.vym and default-dark.vym maps in demos/ directory.

Does it mean this default `default.vym` settings is wrong regarding the text color?

Where is this setting located for text color? Am I supposed to find it somewhere when opening `default.vym` inside of vym directly?

**Comment by insilmaril** [comment]
I hope this is fixed now. Default map is loaded based on dark theme settings, e.g. default-dark.vym or default.vym.

If in "Settings->Set path for new maps"  the "Auto" switch is disabled, new maps will ALWAYS use the given map instead of based on theme.

**Comment by lobre** [comment]
I think this is good now, thank you a lot.

Can I sum up how I think that it works, just for you to confirm my understanding?

So there are no real default values inside the software. Instead, when starting `vym` without any `file`, it will try to load a default project. To know what this default project should be, the following is considered:
- If "Settings -> Set path for new maps > Automatic" is ticked, `vym` will identify if the current environment (say from the desktop) is in light mode or dark mode. Accordingly, it will choose either `/usr/local/share/demos/default.vym` or `/usr/local/share/demos/default-dark.vym`
- But if instead of `Automatic`, we have a path for a specific project, `vym` won't even try to detect light vs dark, as it would be useless. Instead, it will just load that file and colors of the interface will be picked from that default project.

Is that an accurate picture of what happens?

And by seeing that initial default projects are inside of `/usr/local/share/demos/`, I have this other question. Is it normal to put files directly inside a `demos` folder without prefixing with a subdirectory that would group `vym` things together? I have checked the FHS recommendations, and this does not seem to respect that statement:

> Any program or package which contains or requires data that doesn't need to be modified should store that data in /usr/share (or /usr/local/share, if installed locally). It is recommended that a subdirectory be used in /usr/share for this purpose. Applications using a single file may use /usr/share/misc.

https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html

This would be the topic for another issue, but to me, `vym` should create a `/usr/local/share/vym`, and put its `demos`, `scripts`, and so on inside of that, as otherwise, it is a bit of a mess, and it could conflict with other software. And apart from the FHS recommendation, I can see that other softwares on my local system do have that subdirectory concept.

**Comment by insilmaril** [comment]
>     * But if instead of `Automatic`, we have a path for a specific project, `vym` won't even try to detect light vs dark, as it would be useless. Instead, it will just load that file and colors of the interface will be picked from that default project.
> 
> Is that an accurate picture of what happens?
> 
Pretty much, yes: Some color detection still will be done to also window color IF not system setting for "Dark theme" settings is used.

So vym looks within the default maps for a MapDesign. The fallback for that would be settings in mapdesign.cpp.

This concept is still pretty new in vym, so still might see changes. (And until last week the default maps didn't had any MapDesign at all...)


> And by seeing that initial default projects are inside of `/usr/local/share/demos/`, I have this other question. Is it normal to put files directly inside a `demos` folder without prefixing with a subdirectory that would group `vym` things together? I have checked the FHS recommendations, and this does not seem to respect that statement:
...

Hm, yes. The packaging is another topic. For Linux I build (for various distributions) in OBS:

https://build.opensuse.org/projects/home:insilmaril/packages/vym-ng/files/vym.spec?expand=1


Meanwhile vym has again a debian maintainer.  I also build for Mac and Window (currently lacking a decent Windows machine) . So ideally a lot of the logic would go into the cmake file for the install target, but I didn't had the time so far to consider all platforms in cmake (not an expert there...)

> 
> This would be the topic for another issue, but to me, `vym` should create a `/usr/local/share/vym`, and put its `demos`, `scripts`, and so on inside of that, as otherwise, it is a bit of a mess, and it could conflict with other software. And apart from the FHS recommendation, I can see that other softwares on my local system do have that subdirectory concept.

If not strictly required, I wouldn't want to change the cmake setup myself right now, but I am really open for patches :-)
